- hosts: web_portal_server

  tasks:

    - name: update apt cache
      apt: update_cache=yes cache_valid_time=3600
      sudo: yes

    - name: upgrade the distro
      apt: upgrade=yes
      sudo: yes

    - name: install packages
      apt: pkg={{ item }} state=latest
      sudo: yes
      with_items:
        - tomcat
      notify:
        - restart tomcat
    
    - name: forbid SSH root login
      sudo: yes
      lineinfile: destfile=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
      notify:
        - restart ssh

  handlers:

    - name: restart tomcat
      sudo: yes
      action: service name=tomcat state=restarted enabled=yes
    
    - name: restart ssh
      sudo: yes
      action: service name=ssh state=restarted enabled=yes
